### ISSUE TITLE
Unable to retrieve metrics.

### ISSUE THREAD

**Issue by emmceemoore** [pascomnet/kamailio_exporter#7]
I'm getting the following error:

> `curl localhost:9494/metrics`
```
An error has occurred while serving metrics:

collected metric "kamailio_rtpengine_enabled" { label:<name:"index" value:"" > label:<name:"set" value:"" > label:<name:"url" value:"" > label:<name:"weight" value:"" > gauge:<value:0 > } was collected before with the same name and label values
```

I'm not sure if it's relevant or not but I'm _not_ running `rtpengine` on the host in question.

I'm able to work-around the issue by going back to an earlier commit (13f2206563ce7dbf4dd7abf6fcd01009e9b0fd6f).

**Comment by towe75** [comment]
@emmceemoore thank you raising this issue. We'll have a look.
